#include "shaderlib/cshader.h"

#define shaderStaticTest_lightpass_blit_ps30 (0)

class lightpass_blit_ps30_Static_Index
{
public:
	lightpass_blit_ps30_Static_Index( void )
	{
#ifdef _DEBUG
#endif	// _DEBUG
	}

	int GetIndex( void )
	{
		// Asserts to make sure that we aren't using any skipped combinations.

#ifdef _DEBUG
		// Asserts to make sure that we are setting all of the combination vars.
#endif	// _DEBUG

		return 0;
	}

private:
#ifdef _DEBUG
#endif	// _DEBUG
};


#define shaderDynamicTest_lightpass_blit_ps30 (0)

class lightpass_blit_ps30_Dynamic_Index
{
public:
	lightpass_blit_ps30_Dynamic_Index( void )
	{
#ifdef _DEBUG
#endif	// _DEBUG
	}

	int GetIndex( void )
	{
		// Asserts to make sure that we aren't using any skipped combinations.

#ifdef _DEBUG
		// Asserts to make sure that we are setting all of the combination vars.
#endif	// _DEBUG

		return 0;
	}

private:
#ifdef _DEBUG
#endif	// _DEBUG
};
